### ISSUE TITLE
2.6.0 still not supported? 

### ISSUE THREAD

**Issue by fgadaleta** [asyncapi/github-action-for-generator#298]
apparently 2.5.0 either.

**Comment by AchrafAmil** [comment]
having the same issue, what version is supported then? 🤔

**Comment by AchrafAmil** [comment]
As per the tests it should work with `2.0.0`

https://github.com/asyncapi/github-action-for-generator/blob/master/test/asyncapi.yml

(perhaps supporting 2.6.0 is just a one-liner bump PR? 🙏)

**Comment by AchrafAmil** [comment]
yes referring to `uses: docker://asyncapi/github-action-for-generator:2.0.0` but just realized I were stuck on 2.0.0 as per the copy/paste from the action's readme. perhaps pointing to 2.1.12 would have helped but after all I just ended up doing a plain CLI call, something like:
```
- name: Generate md from asyncapi
   run: |
          npm install -g @asyncapi/generator
          ag $YAML_FILE @asyncapi/markdown-template@v1.2.1 -o generated -p frontMatter=$FRONT_MATTER_FILE -p toc=false -p outFilename=doc.md
```

**Comment by derberg** [comment]
thanks for clarification

I strongly recommend you to not use Generator CLI like `npm install -g @asyncapi/generator`

have a look at more details in https://github.com/asyncapi/github-action-for-generator/issues/286#issuecomment-1487154296

closing as all seems to be fine, otherwise please create separate issue
